# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#coding: utf-8

Category.create(:type => '北海道')
Category.create(:type => '青森県')
Category.create(:type => '岩手県')
Category.create(:type => '宮城県')
Category.create(:type => '秋田県')
Category.create(:type => '山形県')
Category.create(:type => '福島県')
Category.create(:type => '茨城県')
Category.create(:type => '栃木県')
Category.create(:type => '群馬県')
Category.create(:type => '埼玉県')
Category.create(:type => '千葉県')
Category.create(:type => '東京都')
Category.create(:type => '神奈川県')
Category.create(:type => '新潟県')
Category.create(:type => '富山県')
Category.create(:type => '石川県')
Category.create(:type => '福井県')
Category.create(:type => '山梨県')
Category.create(:type => '長野県')
Category.create(:type => '岐阜県')
Category.create(:type => '静岡県')
Category.create(:type => '愛知県')
Category.create(:type => '三重県')
Category.create(:type => '滋賀県')
Category.create(:type => '京都府')
Category.create(:type => '大阪府')
Category.create(:type => '兵庫県')
Category.create(:type => '奈良県')
Category.create(:type => '和歌山県')
Category.create(:type => '鳥取県')
Category.create(:type => '島根県')
Category.create(:type => '岡山県')
Category.create(:type => '広島県')
Category.create(:type => '山口県')
Category.create(:type => '徳島県')
Category.create(:type => '香川県')
Category.create(:type => '愛媛県')
Category.create(:type => '高知県')
Category.create(:type => '福岡県')
Category.create(:type => '佐賀県')
Category.create(:type => '長崎県')
Category.create(:type => '熊本県')
Category.create(:type => '大分県')
Category.create(:type => '宮崎県')
Category.create(:type => '鹿児島県')
Category.create(:type => '沖縄県')